--@Autores:         Jorge Cárdenas Cárdenas
--                  Samuel Arturo Garrido Sánchez
--@Fecha creación:  16/08/2021
--@Descripción:     Creación de fragmentos NETMAX_3

-- 
-- TABLE: PROGRAMA_F1_JCC_S1 
--

CREATE TABLE PROGRAMA_F1_JCC_S1(
    PROGRAMA_ID         NUMBER(10, 0)    NOT NULL,
    FOLIO               VARCHAR2(13)     NOT NULL,
    NOMBRE              VARCHAR2(100)    NOT NULL,
    DESCRIPCION         VARCHAR2(500)    NOT NULL,
    FECHA_STATUS        DATE             NOT NULL,
    TIPO                CHAR(1)          NOT NULL,
    STATUS_PROGRAMA_ID  NUMBER(2,0)      NOT NULL,
    CONSTRAINT PROGRAMA_F1_JCC_S1_PK PRIMARY KEY (PROGRAMA_ID)
)
;



-- 
-- TABLE: DOCUMENTAL_F1_JCC_S1 
--

CREATE TABLE DOCUMENTAL_F1_JCC_S1(
    PROGRAMA_ID    NUMBER(10, 0)    NOT NULL,
    TEMATICA       VARCHAR2(100)    NOT NULL,
    DURACION       NUMBER(5, 2)     NOT NULL,
    TRAILER        BLOB             NOT NULL,
    PAIS_ID        NUMBER(2, 0)     NOT NULL,
    CONSTRAINT DOCUMENTAL_F1_JCC_S1_PK PRIMARY KEY (PROGRAMA_ID), 
    CONSTRAINT DOCUMENTAL_F1_PROGRAMA_ID_FK FOREIGN KEY (PROGRAMA_ID)
    REFERENCES PROGRAMA_F1_JCC_S1(PROGRAMA_ID)
)
;



-- 
-- TABLE: PELICULA_F1_JCC_S1 
--

CREATE TABLE PELICULA_F1_JCC_S1(
    PROGRAMA_ID                NUMBER(10, 0)    NOT NULL,
    DURACION                   NUMBER(5, 2)     NOT NULL,
    SINOPSIS                   VARCHAR2(500)    NOT NULL,
    CLASIFICACION              CHAR(1)          NOT NULL,
    PELICULA_ANTECEDENTE_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PELICULA_F1_JCC_S1_PK PRIMARY KEY (PROGRAMA_ID), 
    CONSTRAINT PELICULA_F1_PROGRAMA_ID_FK FOREIGN KEY (PROGRAMA_ID)
    REFERENCES PROGRAMA_F1_JCC_S1(PROGRAMA_ID)
)
;



-- 
-- TABLE: TIPO_CUENTA_MASTER 
--

CREATE TABLE TIPO_CUENTA_MASTER(
    TIPO_CUENTA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE             VARCHAR2(40)     NOT NULL,
    DESCRIPCION       VARCHAR2(500)    NOT NULL,
    COSTO_MENSUAL     NUMBER(10, 2)    NOT NULL,
    CONSTRAINT TIPO_CUENTA_MASTER_PK PRIMARY KEY (TIPO_CUENTA_ID)
)
;



-- 
-- TABLE: USUARIO_F3_JCC_S1 
--

CREATE TABLE USUARIO_F3_JCC_S1(
    USUARIO_ID          NUMBER(10, 0)    NOT NULL,
    EMAIL               VARCHAR2(200)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    FECHA_INGRESO       DATE             NOT NULL,
    FECHA_CUENTA_FIN    DATE,
    VIGENTE             NUMBER(1, 0)     NOT NULL,
    TIPO_CUENTA_ID      NUMBER(2, 0)     NOT NULL,
    CONSTRAINT USUARIO_F3_JCC_S1_PK PRIMARY KEY (USUARIO_ID), 
    CONSTRAINT USUARIO_F3_TIPO_CUENTA_ID_FK FOREIGN KEY (TIPO_CUENTA_ID)
    REFERENCES TIPO_CUENTA_MASTER(TIPO_CUENTA_ID)
)
;



-- 
-- TABLE: PLAYLIST_F2_JCC_S1 
--

CREATE TABLE PLAYLIST_F2_JCC_S1(
    PLAYLIST_ID           NUMBER(10, 0)    NOT NULL,
    CALIFICACION          NUMBER(1, 0)     NOT NULL,
    INDICE                NUMBER(10, 0)    NOT NULL,
    NUM_REPRODUCCIONES    NUMBER(10, 0)    NOT NULL,
    PROGRAMA_ID           NUMBER(10, 0)    NOT NULL,
    USUARIO_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PLAYLIST_F2_JCC_S1_PK PRIMARY KEY (PLAYLIST_ID), 
    CONSTRAINT PLAYLIST_F2_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO_F3_JCC_S1(USUARIO_ID)
)
;



-- 
-- TABLE: SERIE_F1_JCC_S1 
--

CREATE TABLE SERIE_F1_JCC_S1(
    PROGRAMA_ID          NUMBER(10, 0)    NOT NULL,
    NUM_CAPITULOS        NUMBER(3, 0)     NOT NULL,
    DURACION_CAPITULO    NUMBER(5, 2)     NOT NULL,
    TIPO_SERIE_ID        NUMBER(2, 0),
    CONSTRAINT SERIE_F1_JCC_S1_PK PRIMARY KEY (PROGRAMA_ID), 
    CONSTRAINT SERIE_F1_PROGRAMA_ID_FK FOREIGN KEY (PROGRAMA_ID)
    REFERENCES PROGRAMA_F1_JCC_S1(PROGRAMA_ID)
)
;



-- 
-- TABLE: STATUS_PROGRAMA_JCC_S1 
--

CREATE TABLE STATUS_PROGRAMA_JCC_S1(
    STATUS_PROGRAMA_ID    NUMBER(2, 0)     NOT NULL,
    DESCRIPCION           VARCHAR2(40)     NOT NULL,
    CLAVE                 VARCHAR2(500)    NOT NULL,
    CONSTRAINT STATUS_PROGRAMA_JCC_S1_PK PRIMARY KEY (STATUS_PROGRAMA_ID)
)
;



-- 
-- INDEX: PLAYLIST_F2_USUARIO_ID_IX 
--

CREATE INDEX PLAYLIST_F2_USUARIO_ID_IX ON PLAYLIST_F2_JCC_S1(USUARIO_ID)
;
-- 
-- INDEX: USUARIO_F3_TIPO_CUENTA_ID_IX 
--

CREATE INDEX USUARIO_F3_TIPO_CUENTA_ID_IX ON USUARIO_F3_JCC_S1(TIPO_CUENTA_ID)
;
-- 
-- SYNONYM: USUARIO_1 
--
