--@Autores:         Jorge Cárdenas Cárdenas
--                  Samuel Arturo Garrido Sánchez
--@Fecha creación:  16/08/2021
--@Descripción:     Creación de fragmentos NETMAX_3

CREATE TABLE ARCHIVO_PROGRAMA_F2_SGS_S1(
    NUM_ARCHIVO    NUMBER(5, 0)     NOT NULL,
    PROGRAMA_ID    NUMBER(10, 0)    NOT NULL,
    ARCHIVO        BLOB             NOT NULL,
    TAMANIO        NUMBER(10, 2)    NOT NULL,
    CONSTRAINT ARCHIVO_PROGRAMA_F2_SGS_S1_PK 
    PRIMARY KEY (NUM_ARCHIVO, PROGRAMA_ID)
    ON DELETE CASCADE
);

CREATE TABLE PAIS_R_SGS_S1(
    PAIS_ID       NUMBER(2, 0)    NOT NULL,
    CLAVE         VARCHAR2(4)     NOT NULL,
    NOMBRE        VARCHAR2(50)    NOT NULL,
    CONTINENTE    VARCHAR2(3)     NOT NULL,
    CONSTRAINT PAIS_MASTER_PK 
    PRIMARY KEY (PAIS_ID)
    ON DELETE CASCADE
);

CREATE TABLE STATUS_PROGRAMA_SGS_S1(
    STATUS_PROGRAMA_ID    NUMBER(2, 0)     NOT NULL,
    DESCRIPCION           VARCHAR2(500)     NOT NULL,
    CLAVE                 VARCHAR2(40)    NOT NULL,
    CONSTRAINT STATUS_PROGRAMA_SGS_S1_PK 
    PRIMARY KEY (STATUS_PROGRAMA_ID)
    ON DELETE CASCADE
);

CREATE TABLE PROGRAMA_F2_SGS_S1(
    PROGRAMA_ID           NUMBER(10, 0)    NOT NULL,
    FOLIO                 VARCHAR2(13)     NOT NULL,
    NOMBRE                VARCHAR2(100)    NOT NULL,
    DESCRIPCION           VARCHAR2(500)    NOT NULL,
    FECHA_STATUS          DATE             NOT NULL,
    TIPO                  CHAR(1)          NOT NULL,
    STATUS_PROGRAMA_ID    NUMBER(2, 0)     NOT NULL,
    CONSTRAINT PROGRAMA_F2_SGS_S1_PK PRIMARY KEY (PROGRAMA_ID), 
    CONSTRAINT PROGRAMA_F2_SGS_S1_STATUS_PROGRAMA_ID_FK FOREIGN KEY (STATUS_PROGRAMA_ID)
    REFERENCES STATUS_PROGRAMA_SGS_S1(STATUS_PROGRAMA_ID)
    ON DELETE CASCADE
);

CREATE TABLE DOCUMENTAL_F2_SGS_S1(
    PROGRAMA_ID    NUMBER(10, 0)    NOT NULL,
    TEMATICA       VARCHAR2(100)    NOT NULL,
    DURACION       NUMBER(5, 2)     NOT NULL,
    TRAILER        BLOB             NOT NULL,
    PAIS_ID        NUMBER(2, 0)     NOT NULL,
    CONSTRAINT DOCUMENTAL_F2_SGS_S1_PK PRIMARY KEY (PROGRAMA_ID), 
    CONSTRAINT DOCUMENTAL_F2_SGS_S1_PAIS_ID_FK FOREIGN KEY (PAIS_ID)
    REFERENCES PAIS_R_SGS_S1(PAIS_ID),
    CONSTRAINT DOCUMENTAL_F2_SGS_S1_PROGRAMA_ID_FK FOREIGN KEY (PROGRAMA_ID)
    REFERENCES PROGRAMA_F2_SGS_S1(PROGRAMA_ID)
    ON DELETE CASCADE
);

CREATE TABLE PELICULA_F2_SGS_S1(
    PROGRAMA_ID                NUMBER(10, 0)    NOT NULL,
    DURACION                   NUMBER(5, 2)     NOT NULL,
    SINOPSIS                   VARCHAR2(500)    NOT NULL,
    CLASIFICACION              CHAR(1)          NOT NULL,
    PELICULA_ANTECEDENTE_ID    NUMBER(10, 0),
    CONSTRAINT PELICULA_F2_SGS_S1_PK PRIMARY KEY (PROGRAMA_ID), 
    CONSTRAINT PELICULA_F2_SGS_S1_PROGRAMA_ID_FK FOREIGN KEY (PROGRAMA_ID)
    REFERENCES PROGRAMA_F2_SGS_S1(PROGRAMA_ID)
    ON DELETE CASCADE
);

CREATE TABLE TIPO_CUENTA_R_SGS_S1(
    TIPO_CUENTA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE             VARCHAR2(40)     NOT NULL,
    DESCRIPCION       VARCHAR2(500)    NOT NULL,
    COSTO_MENSUAL     NUMBER(10, 2)    NOT NULL,
    CONSTRAINT TIPO_CUENTA_R_SGS_S1_PK PRIMARY KEY (TIPO_CUENTA_ID)
    ON DELETE CASCADE
);

CREATE TABLE USUARIO_F4_SGS_S1(
    USUARIO_ID          NUMBER(10, 0)    NOT NULL,
    EMAIL               VARCHAR2(200)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    FECHA_INGRESO       DATE             NOT NULL,
    FECHA_CUENTA_FIN    DATE,
    VIGENTE             NUMBER(1, 0)     NOT NULL,
    TIPO_CUENTA_ID      NUMBER(2, 0)     NOT NULL,
    CONSTRAINT USUARIO_F4_SGS_S1_PK PRIMARY KEY (USUARIO_ID), 
    CONSTRAINT USUARIO_F4_SGS_S1_TIPO_CUENTA_ID_FK FOREIGN KEY (TIPO_CUENTA_ID)
    REFERENCES TIPO_CUENTA_R_SGS_S1(TIPO_CUENTA_ID)
    ON DELETE CASCADE
);

CREATE TABLE PLAYLIST_F3_SGS_S1(
    PLAYLIST_ID           NUMBER(10, 0)    NOT NULL,
    CALIFICACION          NUMBER(1, 0)     NOT NULL,
    INDICE                NUMBER(10, 0)    NOT NULL,
    NUM_REPRODUCCIONES    NUMBER(10, 0)    NOT NULL,
    PROGRAMA_ID           NUMBER(10, 0)    NOT NULL,
    USUARIO_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PLAYLIST_F3_SGS_S1_PK PRIMARY KEY (PLAYLIST_ID), 
    CONSTRAINT PLAYLIST_F3_SGS_S1_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO_F4_SGS_S1(USUARIO_ID)
    ON DELETE CASCADE
);

CREATE TABLE TIPO_SERIE_R_SGS_S1(
    TIPO_SERIE_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE            VARCHAR2(40)     NOT NULL,
    DESCRIPCION      VARCHAR2(500)    NOT NULL,
    CONSTRAINT TIPO_SERIE_R_SGS_S1_PK PRIMARY KEY (TIPO_SERIE_ID)
    ON DELETE CASCADE
);

CREATE TABLE SERIE_F2_SGS_S1(
    PROGRAMA_ID          NUMBER(10, 0)    NOT NULL,
    NUM_CAPITULOS        NUMBER(3, 0)     NOT NULL,
    DURACION_CAPITULO    NUMBER(5, 2)     NOT NULL,
    TIPO_SERIE_ID        NUMBER(2, 0)     NOT NULL,
    CONSTRAINT SERIE_F2_SGS_S1_PK PRIMARY KEY (PROGRAMA_ID), 
    CONSTRAINT SERIE_F2_SGS_S1_TIPO_SERIE_ID_FK FOREIGN KEY (TIPO_SERIE_ID)
    REFERENCES TIPO_SERIE_R_SGS_S1(TIPO_SERIE_ID),
    CONSTRAINT SERIE_F2_SGS_S1_PROGRAMA_ID_FK FOREIGN KEY (PROGRAMA_ID)
    REFERENCES PROGRAMA_F2_SGS_S1(PROGRAMA_ID)
    ON DELETE CASCADE
);

CREATE TABLE USUARIO_F1_SGS_S1(
    USUARIO_ID     NUMBER(10, 0)    NOT NULL,
    NUM_TARJETA    VARCHAR2(16)     NOT NULL,
    PASSWORD       VARCHAR2(16)     NOT NULL,
    CONSTRAINT USUARIO_F1_SGS_S1_PK PRIMARY KEY (USUARIO_ID)
    ON DELETE CASCADE
);

CREATE INDEX DOCUMENTAL_F2_SGS_S1_PAIS_ID_IX ON DOCUMENTAL_F2_SGS_S1(PAIS_ID);

CREATE INDEX PLAYLIST_F3_SGS_S1_USUARIO_ID_IX ON PLAYLIST_F3_SGS_S1(USUARIO_ID);